"""epic_7_manual_transaction_management

Revision ID: 266802e01e3d
Revises: 76dec616d384
Create Date: 2025-10-28 05:44:23.285548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '266802e01e3d'
down_revision: Union[str, Sequence[str], None] = '76dec616d384'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('source', sa.String(length=20), nullable=True))
    op.add_column('transactions', sa.Column('notes', sa.String(length=500), nullable=True))
    op.add_column('transactions', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_transactions_source'), 'transactions', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_source'), table_name='transactions')
    op.drop_column('transactions', 'deleted_at')
    op.drop_column('transactions', 'notes')
    op.drop_column('transactions', 'source')
    # ### end Alembic commands ###
