"""Initial migration - create all tables

Revision ID: 76dec616d384
Revises: 
Create Date: 2025-10-21 09:45:48.135247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76dec616d384'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.DateTime(), nullable=False),
    sa.Column('total_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('cash_balance', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('invested_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_cost_basis', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_unrealized_pnl', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_unrealized_pnl_percent', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('total_realized_pnl', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('positions_snapshot', sa.JSON(), nullable=True),
    sa.Column('metals_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('stocks_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('crypto_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('cash_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_portfolio_snapshots_date', 'portfolio_snapshots', [sa.literal_column('snapshot_date DESC')], unique=False)
    op.create_index(op.f('ix_portfolio_snapshots_snapshot_date'), 'portfolio_snapshots', ['snapshot_date'], unique=True)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_date', sa.DateTime(), nullable=False),
    sa.Column('asset_type', sa.Enum('METAL', 'STOCK', 'CRYPTO', name='assettype'), nullable=False),
    sa.Column('transaction_type', sa.Enum('BUY', 'SELL', 'DIVIDEND', 'STAKING', 'FEE', 'TRANSFER', 'CASH_IN', 'CASH_OUT', name='transactiontype'), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('price_per_unit', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('fee', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('cost_basis', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('tax_lot_id', sa.String(length=100), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('source_file', sa.String(length=255), nullable=True),
    sa.Column('source_type', sa.String(length=10), nullable=True),
    sa.Column('import_timestamp', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_date', 'symbol', 'quantity', 'transaction_type', 'asset_type', name='uix_transaction_unique')
    )
    op.create_index('idx_transactions_date_symbol', 'transactions', ['transaction_date', 'symbol'], unique=False)
    op.create_index('idx_transactions_import', 'transactions', ['import_timestamp'], unique=False)
    op.create_index(op.f('ix_transactions_asset_type'), 'transactions', ['asset_type'], unique=False)
    op.create_index(op.f('ix_transactions_source_file'), 'transactions', ['source_file'], unique=False)
    op.create_index(op.f('ix_transactions_symbol'), 'transactions', ['symbol'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_date'), 'transactions', ['transaction_date'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_type'), 'transactions', ['transaction_type'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('asset_type', sa.Enum('METAL', 'STOCK', 'CRYPTO', name='assettype'), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('avg_cost_basis', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('total_cost_basis', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('first_purchase_date', sa.DateTime(), nullable=True),
    sa.Column('last_transaction_date', sa.DateTime(), nullable=True),
    sa.Column('cost_lots', sa.JSON(), nullable=True),
    sa.Column('current_price', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('current_value', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('unrealized_pnl', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('unrealized_pnl_percent', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('last_price_update', sa.DateTime(), nullable=True),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_positions_symbol_type', 'positions', ['symbol', 'asset_type'], unique=False)
    op.create_index(op.f('ix_positions_symbol'), 'positions', ['symbol'], unique=True)
    op.create_table('price_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('asset_type', sa.Enum('METAL', 'STOCK', 'CRYPTO', name='assettype'), nullable=False),
    sa.Column('price_date', sa.DateTime(), nullable=False),
    sa.Column('open_price', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('high_price', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('low_price', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('close_price', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('volume', sa.Numeric(precision=18, scale=0), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'price_date', 'source', name='uix_price_history_unique')
    )
    op.create_index('idx_price_history_symbol_date', 'price_history', ['symbol', 'price_date'], unique=False)
    op.create_index(op.f('ix_price_history_price_date'), 'price_history', ['price_date'], unique=False)
    op.create_index(op.f('ix_price_history_symbol'), 'price_history', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_price_history_symbol'), table_name='price_history')
    op.drop_index(op.f('ix_price_history_price_date'), table_name='price_history')
    op.drop_index('idx_price_history_symbol_date', table_name='price_history')
    op.drop_table('price_history')
    op.drop_index(op.f('ix_positions_symbol'), table_name='positions')
    op.drop_index('idx_positions_symbol_type', table_name='positions')
    op.drop_table('positions')
    op.drop_index(op.f('ix_transactions_transaction_type'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_transaction_date'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_symbol'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_source_file'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_asset_type'), table_name='transactions')
    op.drop_index('idx_transactions_import', table_name='transactions')
    op.drop_index('idx_transactions_date_symbol', table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_portfolio_snapshots_snapshot_date'), table_name='portfolio_snapshots')
    op.drop_index('idx_portfolio_snapshots_date', table_name='portfolio_snapshots')
    op.drop_table('portfolio_snapshots')
    # ### end Alembic commands ###
